### ISSUE TITLE
similar script...

### ISSUE THREAD

**Issue by anarcat** [ianw/photo-scripts#1]
Hi!

I wrote something somewhat similar here:

http://src.anarc.at/scripts.git/blob/HEAD:/photos-import

It's all in one script instead of many, and doesn't do any geotagging or IPTC. I didn't know about IPTC and find it really interesting! It somewhat breaks with my workflow because I do a first batch of pre-processing where I import only a select set of photos from the card (the remaining which should normally be deleted by the camera). I do this with the `fim` image viewer. It would be nice if i could add descriptions during that process as well...

Part of my workflow is to use git-annex for storage and replication, and darktable for post-processing, so that's a little peculiar as well. I am using exiftool to move the photos around like your `move-by-date` script does - and I have been very frustrated with the way exiftool works there, maybe I will reuse your scripts and/or libraries to rewrite this in Python!

I do not publish _all_ my photos online, so that part is omitted as well (it is left to Darktable to process the photos and put them in a location that Photofloat will then process).

So in short, I also rolled my own image importer, but reused a bunch of existing tools (fim, exiftool, git-annex, darktable) instead of re-creating everything from scratch. I am somewhat worried about those dependencies, but i feel darktable and git-annex will be there for a while, and you just gave me good pointers on how to replace exiftool, so I might just do exactly that. As for fim, it has been in Debian for a long time (but removed during some time) - yet i feel it's reasonable to expect something similar will exist for a while. Failing that, one would just have to fire up some GTK widget to display the images from Python to replace it, since the functionality is so small...

It's somewhat amazing that with all those tools around, we all end up rewriting our own! :)

I wanted to comment on your blog but couldn't find a place for it there, and figured you would see this, sorry if this is inappropriate! :)

**Comment by ianw** [comment]
Cool, I'd never heard of fim which sounds interesting too.

I think it's fine we all have our ways of doing things.  Not everyone arranges the tools in their workbench the same way, but it's always interesting to see how others do things and pick the bits that work for you
